### ISSUE TITLE
500 error when trying to reset password

### ISSUE THREAD

**Issue by gschorkopf** [frolfr/frolfr-server#167]
![screen shot 2015-06-03 at 11 24 34 am](https://cloud.githubusercontent.com/assets/2623668/7963926/30532b3c-09e3-11e5-98b2-152f4a24db89.png)

**Comment by gschorkopf** [comment]
From the heroku stack trace:

```
Started POST "/api/password_resets" for 73.43.57.222 at 2015-06-03 15:27:22 +0000
Processing by Api::PasswordResetsController#create as JSON
Parameters: {"password_reset"=>"[FILTERED]"}

Can't verify CSRF token authenticity
ActionView::MissingTemplate (Missing template user_mailer/password_reset with "mailer". Searched in:
  * "user_mailer"
):
  app/mailers/user_mailer.rb:6:in `password_reset'
  app/models/user.rb:69:in `update_password_reset_token!'
  app/controllers/api/password_resets_controller.rb:14:in `create'

**Comment by gschorkopf** [comment]
Cleaned up, issue resolved in silly mistake from a while ago: https://github.com/frolfr/frolfr-server/commit/3bb39ee8bcff622a717c59ebbf713394972073e6

![screen shot 2015-06-15 at 6 43 55 pm](https://cloud.githubusercontent.com/assets/2623668/8172445/984cfa10-138e-11e5-993d-e9c2e99ccc5f.png)
